name: moreiras_sports_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2

  # Firebase
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8
  firebase_auth: ^4.17.8
  firebase_storage: ^11.6.9

  # State Management
  flutter_riverpod: ^2.5.1

  # Routing
  go_router: ^13.2.4

  # Utilities
  intl: ^0.19.0 # Para datas
  image_picker: ^1.0.7 # Para upload de imagens pelo admin
  cached_network_image: ^3.3.1 # Para exibir imagens da internet com cache
  lottie: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# A seção 'flutter' começa aqui, sem espaços antes.
flutter:

  # 'uses-material-design' e 'assets' estão DENTRO de 'flutter',
  # por isso têm 2 espaços de indentação.
  uses-material-design: true
  assets:
    # Os itens da lista de assets estão DENTRO de 'assets',
    # por isso têm 4 espaços de indentação.
    - assets/images/
    - assets/animations/
