name: moreiras_sports_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# A linha 'dependencies:' NÃO deve ter nenhum espaço antes dela.
dependencies:
  # Cada dependência aqui deve ter EXATAMENTE 2 espaços antes.
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2

  # Firebase
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8
  firebase_auth: ^4.17.8
  firebase_storage: ^11.6.9

  # State Management
  flutter_riverpod: ^2.5.1

  # Routing
  go_router: ^13.2.4

  # Utilities
  intl: ^0.19.0 # Para datas
  image_picker: ^1.0.7 # Para upload de imagens pelo admin
  cached_network_image: ^3.3.1 # Para exibir imagens da internet com cache
  lottie: ^3.3.2

# Se você tiver dependências de desenvolvimento, elas viriam aqui, também alinhadas à esquerda
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


assets:
    - assets/images/
    - assets/animations/