// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_x9KNOHerG2PrkixzsN9ITe3E2DT0VPE',
    appId: '1:879583028035:web:8231fc25a847929f4905f6',
    messagingSenderId: '879583028035',
    projectId: 'moreiras-sports-app',
    authDomain: 'moreiras-sports-app.firebaseapp.com',
    storageBucket: 'moreiras-sports-app.firebasestorage.app',
    measurementId: 'G-GRTNGC3DHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlDp0kj49eBcYz4e6lHLDpNkn7NZ9P0OE',
    appId: '1:879583028035:android:852acc00ea6256254905f6',
    messagingSenderId: '879583028035',
    projectId: 'moreiras-sports-app',
    storageBucket: 'moreiras-sports-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlbu-Elt4DII16zIWIxL2BRa6cFxt8Ayk',
    appId: '1:879583028035:ios:3a3c8d8c082e3a904905f6',
    messagingSenderId: '879583028035',
    projectId: 'moreiras-sports-app',
    storageBucket: 'moreiras-sports-app.firebasestorage.app',
    iosBundleId: 'com.moreiras.moreirasSportsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlbu-Elt4DII16zIWIxL2BRa6cFxt8Ayk',
    appId: '1:879583028035:ios:3a3c8d8c082e3a904905f6',
    messagingSenderId: '879583028035',
    projectId: 'moreiras-sports-app',
    storageBucket: 'moreiras-sports-app.firebasestorage.app',
    iosBundleId: 'com.moreiras.moreirasSportsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_x9KNOHerG2PrkixzsN9ITe3E2DT0VPE',
    appId: '1:879583028035:web:6ba618a202e82d144905f6',
    messagingSenderId: '879583028035',
    projectId: 'moreiras-sports-app',
    authDomain: 'moreiras-sports-app.firebaseapp.com',
    storageBucket: 'moreiras-sports-app.firebasestorage.app',
    measurementId: 'G-D6HC4CF6B7',
  );
}
